---
all:
  children:
    controller:
      hosts:
        localhost:
          ansible_host: localhost
    desktop:
      hosts:
        garkbit:
          ansible_host: garkbit
    pinet:
      hosts:
        rpi:
          ansible_host: rpi
