---
- name: Cargo - Install Common Packages
  hosts: all
  gather_facts: true
  vars:
    cargo_bin: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/cargo"

  pre_tasks:
    - name: Inspect Environment
      ansible.builtin.debug:
        msg:
          - "cargo_bin: {{ cargo_bin }}"
      tags:
        - rust
        - cargo

  tasks:
    - name: Common Packages
      community.general.cargo:
        executable: "{{ cargo_bin }}"
        state: latest
        locked: true
        name:
          - bat # better cat
          - bkt # subprocess caching utility
          - cargo-show # print package metadata
          - du-dust # better du
          - eza # better ls
          - fd-find # better find
          - git-delta # nice diff
          - ripgrep # better grep
          - starship # shell prompt
          - tealdeer # tldr client
      tags:
        - packages
        - user
        - rust
        - cargo

    - name: Uninstall Superseded Packages
      community.general.cargo:
        executable: "{{ cargo_bin }}"
        state: absent
        name:
          - exa # replaced by eza
      tags:
        - packages
        - user
        - rust
        - cargo

- name: Cargo - Install Desktop Packages
  hosts: desktop
  gather_facts: true
  vars:
    cargo_bin: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/cargo"

  tasks:
    - name: Desktop Packages
      community.general.cargo:
        executable: "{{ cargo_bin }}"
        state: latest
        locked: true
        name:
          - alacritty
      tags:
        - packages
        - user
        - rust
        - cargo
