---
- name: PIP - Remove Packages Managed Elsewhere
  hosts: all
  gather_facts: false
  tasks:
    - name: Remove PIP Packages
      ansible.builtin.pip:
        name:
          - ipython
          - pipx
        extra_args: "--user"
        state: absent
      tags:
        - packages
        - user
        - python
        - pip
