---
- name: Reboot Machines
  hosts: desktop
  become: true
  tasks:
    - name: Reboot hosts with no mercy
      ansible.builtin.reboot:
        pre_reboot_delay: 15
        post_reboot_delay: 30
      tags:
        - system
        - reboot
