import = [
    "~/.config/alacritty/themes/catppuccin_mocha.toml",
    "~/.config/alacritty/fonts.toml",
]

live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[env]
TERM = "xterm-256color"

[scrolling]
history = 100000
multiplier = 3

[window]
decorations = "None"
dynamic_padding = true
opacity = 0.95

[window.padding]
x = 4
y = 4
